### PR TITLE
Added size options

### PR DESCRIPTION
**Pull request by JaffParker**

### CODE REVIEW

**Comment by Fi1osof** [comment]
@JaffParker i think this solves size options too? https://github.com/nbudin/react-bootstrap4-modal/pull/5

**Comment by nbudin** [comment]
@Fi1osof: Yup, #5 also solves it by allowing overriding `classNames`.  But, I think we can do both things - make it possible to customize but also provide an easy way to do sizing without having to dive into Bootstrap classes.

**Comment by nbudin** [comment]
Actually, nope, we're wrong - #5 doesn't solve it, because the size classes have to be added to the `modal-dialog` div rather than the `modal` div.  I'm going to try to extend what #5 does to allow adding classes to the `modal-dialog` too.

**Comment by nbudin** [comment]
OK, 1.2.0 (just released) now allows passing `dialogClassName` which lets you add size classes.  It would still be cool to have a version of this feature that makes it more convenient to add size classes using a `oneOf` prop, though!

**Pull request closed without merging**
